# Define front matter defaults
# <http://jekyllrb.com/docs/configuration/#front-matter-defaults>

title: theJubster

description: "Collected stuff from a technically-minded practioner of morosophy.<hr /><br />
 Undoubtedly existing solely to confirm the inherent wisdom in the adage,
  \"A little knowledge in the wrong hands can be a dangerous thing\"."


github_username: 'thejubster'
bitbucket_username: 'thejubster'
twitter_username:



defaults:

  -
    scope:
      path: ""
      author: "theJubster"

  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
      category: "posts"

  -
    scope:
      path: "projects"
      type: "project"
    values:
      layout: "project"
      category: "project"

  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
      category: "pages"



# Where things are
# source:      .   # <-- Disabled on githubpages
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
# safe:         false ## <-- Disabled on githubpages
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
#markdown:    kramdown
markdown:    redcarpet
#highlighter: rouge
higlighter: pygments
# lsi:         false ## <-- Disabled on github pages

#excerpt_separator: "\n\n"
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors

redcarpet:
  extensions: [

    #do not parse emphasis inside of words. Strings such as foo_bar_baz will not generate <em> tags
    "no_intra_emphasis",
    #parse tables, PHP-Markdown style.
    "tables",
    #parse fenced code blocks, PHP-Markdown style. Blocks delimited with 3 or more ~ or backticks will be considered as code, without the need to be indented. An optional language name may be added at the end of the opening fence for the code block.
    "fenced_code_blocks",
    #parse links even when they are not enclosed in <> characters. Autolinks for the http, https and ftp protocols will be automatically detected. Email addresses and http links without protocol, but starting with www are also handled.
    "autolink",
    #do not parse usual markdown code blocks. Markdown converts text with four spaces at the front of each line to code blocks. This options prevents it from doing so. Recommended to use with fenced_code_blocks: true.
    "disable_indented_code_blocks",
    #parse strikethrough, PHP-Markdown style. Two ~ characters mark the start of a strikethrough, e.g. this is ~~good~~ bad.
    "strikethrough",
    #HTML blocks do not require to be surrounded by an empty line as in the Markdown standard.
    "lax_spacing",
    #A space is always required between the hash at the beginning of a header and its name, e.g. #this is my header would not be a valid header.
    "space_after_headers",
    #parse superscripts after the ^ character; contiguous superscripts are nested together, and complex values can be enclosed in parenthesis, e.g. this is the 2^(nd) time.
    "superscript",
    #parse underscored emphasis as underlines. This is _underlined_ but this is still *italic*.
    "underline",
    #parse highlights. This is ==highlighted==. It looks like this: <mark>highlighted</mark>
    "highlight",
    #parse quotes. This is a "quote". It looks like this: <q>quote</q>
    "quote",
    #parse footnotes, PHP-Markdown style. A footnote works very much like a reference-style link: it consists of a marker next to the text (e.g. This is a sentence.[^1]) and a footnote definition on its own line anywhere within the document (e.g. [^1]: This is a footnote.).
    "footnotes"

  ]



kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         2
    coderay_bold_every:        10
    #coderay_css:               style
    coderay_css:               class
