# Define front matter defaults
# <http://jekyllrb.com/docs/configuration/#front-matter-defaults>

github_username: "thejubster"

defaults:

  -
    scope:
      path: ""
      author: "theJubster"

  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
      category: "posts"

  -
    scope:
      path: "projects"
      type: "project"
    values:
      layout: "project"
      category: "project"

  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
      category: "pages"



# Where things are
# source:      .   # <-- Disabled on githubpages
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
# safe:         false ## <-- Disabled on githubpages
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
#highlighter: rouge
higlighter: pygments
# lsi:         false ## <-- Disabled on github pages

excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
